version: "3.7"

services:
  user_service:
    image: risk-management/user-service
    build: ./backend/user-service
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres-net
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresql:5432/insurance_risks
    depends_on:
      - postgresql
    volumes:
      - .m2:/root/.m2

  policy_service:
    image: risk-management/policy-service
    build: ./backend/policy-service
    restart: always
    ports:
      - 8081:8081
    networks:
      - postgres-net
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresql:5432/insurance_risks?currentSchema=policy_schema
    depends_on:
      - postgresql
    volumes:
      - .m2:/root/.m2

  front_end:
    image: risk-management/frontend
    build: ./client
    restart: always
    ports:
      - 3000:3000

  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - postgres-net
    environment:
      POSTGRES_DB: insurance_risks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

networks:
  postgres-net:
